#!/bin/bash
# Sync submodule READMEs into Claude Code context
#
# This script:
# 1. Lists all git submodules in the current repo
# 2. Generates @import statements for their READMEs
# 3. Writes to .claude/submodule-context.md
#
# Claude Code's CLAUDE.md can then @import this file to get all submodule context.
#
# Usage: ./scripts/sync-submodule-context.sh [repo_path]

REPO_PATH="${1:-.}"
cd "$REPO_PATH" || exit 1

OUTPUT_FILE=".claude/submodule-context.md"
mkdir -p .claude

# Start fresh
cat > "$OUTPUT_FILE" << 'EOF'
# Submodule Context (Auto-Generated)

This file is auto-generated by `scripts/sync-submodule-context.sh`.
Do not edit manually - it will be overwritten.

The following submodule READMEs are imported into context:

EOF

# Get all submodules and their paths
if [ -f .gitmodules ]; then
    git submodule foreach --quiet 'echo "$sm_path"' | while IFS= read -r submodule_path; do
        readme_path="$submodule_path/README.md"

        if [ -f "$readme_path" ]; then
            echo "## $submodule_path" >> "$OUTPUT_FILE"
            echo "" >> "$OUTPUT_FILE"
            echo "@$readme_path" >> "$OUTPUT_FILE"
            echo "" >> "$OUTPUT_FILE"
            echo "Found: $readme_path" >&2
        else
            echo "Skipped (no README): $submodule_path" >&2
        fi
    done
else
    echo "No .gitmodules found - no submodules to import" >&2
    echo "*No submodules found.*" >> "$OUTPUT_FILE"
fi

echo "" >> "$OUTPUT_FILE"
echo "---" >> "$OUTPUT_FILE"
echo "*Last synced: $(date)*" >> "$OUTPUT_FILE"

echo "Context file written to: $OUTPUT_FILE" >&2
